#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKx50MQ3Az61VStuCo+q0d/xFeN6X1hSPcmRfeqqtC4vynwnoul74LkyJm5/cbaPcujxqTDXYafiGANRWv5p4qQ3KWxs5WrBry41fuP2ETOx6gFp6pI3m75uYKSUertqF6MxZ53Mac+Vy112YYnM3O3VIK4j7blPyIUSIEVmeqBIrVR0StFXlJcH4A2i6V30Ccnma
        3HFdPCsyPhhO3XnQ8hK9sfyR8ZotqVwRTxgBTplh/GTe3K+iVtqgcTGEyf3cyQ6RJU4rg3fPmL/LniC9x4fMwc/aheH/hu0hPeRH2uELC9YvQ2iPhSs8fwJGrE6CE1rpGpeGPNDtO+l7pBQpwRLzqpSfqfFA0/mGP70tqApCx7iPE+k2O9vHvuVboA6saCxTaKHGNgR10a8JTzqCmq37G+3SDwe8P/axiT8+z8BYahS
        f17sHOypgcv7gJTav7WcMVeP5bvqLoRU14hd3O1aeyHpl6G5mgAUKGSwg4fQIYdCGvMxpXQ0gYTV/YF30=

# Downloads the apache2 package
packages:
  - apache2

# Configures apache2
runcmd:
  - sudo systemctl start apache2
  - sudo systemctl enable apache2